<div class="row">
    <div class="col-md-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">People in the Guestbook</h3>
            </div>
            <div class="panel-body">
                <table width="100%">
                <tr>
                    <th width="20%">Name</th>
                    <th width="25%">Email</th>
                    <th width="25%">Website</th>
                    <th width="30%">Message</th>
                </tr>
                <?php foreach ($this->guestList as $guest) : ?>
                <tr>
                    <td width="20%"><?= $guest->name; ?></td>
                    <td width="25%"><?= $guest->email; ?></td>
                    <td width="25%"><?= $guest->website; ?></td>
                    <td width="30%"><?= $guest->message; ?></td>
                </tr>
                <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>

</div>
